/* AvacaDO: standalone browser board game. State is persisted locally. */
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const FRUITS=[['Tomato','🍅','#db5147'],['Strawberry','🍓','#d64549'],['Orange','🍊','#e78928'],['Potato','🥔','#aa8452'],['Banana','🍌','#e6cb43']];
const TYPES={normal:['normal','REST'],roll:['roll','ROLL AGAIN'],back:['back','BACK 5'],swap:['swap','SWAP'],event:['event','EVENT'],bad:['bad','BAD LUCK'],goal:['goal','GOAL']};
const EVENTS=[
 ['Royal Shortcut','🌿','Move forward 6 spaces.',p=>move(p,6)],['Rebel Feast','🍞','Gain 6 points.',p=>p.points+=6],['Tax Collector','🪙','Lose 4 points.',p=>p.points=Math.max(0,p.points-4)],['Hidden Tunnel','🕳️','Move forward 4 spaces.',p=>move(p,4)],['Royal Mud','🫧','Move back 4 spaces.',p=>move(p,-4)],['Rebel Banner','🚩','Take another turn!',p=>p.extra=true],['King’s Decree','📜','Skip your next turn.',p=>p.skip++],['Secret Map','🗺️','Gain 8 points.',p=>p.points+=8],['Cado Guard','🛡️','A rival is blocked for one turn.',p=>{let r=rival(p);if(r)r.skip++}],['Market Day','🏰','Gain 4 points.',p=>p.points+=4],['Ripe Escape','💨','Move forward 3 spaces.',p=>move(p,3)],['Spoiled Supplies','🦠','Lose 3 points.',p=>p.points=Math.max(0,p.points-3)],['Mirror Portal','🪞','Swap places with a rival.',p=>swap(p,rival(p))],['Lucky Seed','🌱','Gain a free +3 boost.',p=>p.boost3=1],['Sabotage','💣','A rival loses 5 points.',p=>{let r=rival(p);if(r)r.points=Math.max(0,r.points-5)}],['Royal Road','🐎','Move forward 5 spaces.',p=>move(p,5)],['Rebel Spy','🕵️','Reveal: gain 2 points and another turn.',p=>{p.points+=2;p.extra=true}],['Broken Cart','🛒','Move back 3 spaces.',p=>move(p,-3)],['Shield Charm','✨','Gain 2 turns of immunity.',p=>p.immunity=Math.max(p.immunity,2)],['Cado Curse','👑','Doomsday loses 2 turns!',p=>game.clock=Math.min(game.maxClock,game.clock+2)] ];
let game=null, audio=null;
function tileType(i){if(i===75)return'goal';const event=[3,7,11,15,19,23,27,31,35,39,43,47,51,55,59,63,67,69,71,73];if(event.includes(i))return'event';if([9,29,49,65].includes(i))return'roll';if([13,33,53].includes(i))return'back';if([17,37,57].includes(i))return'swap';if([21,45,61].includes(i))return'bad';return'normal'}
function save(){if(game)localStorage.setItem('avacadoSave',JSON.stringify(game));}
function clearSave(){localStorage.removeItem('avacadoSave');$('#continueBtn').classList.add('hidden');}
function show(id){$$('.screen,#gameScreen').forEach(x=>x.classList.add('hidden'));$('#'+id).classList.remove('hidden')}
function setup(){show('setupScreen');$('#playerSetup').innerHTML=FRUITS.map((f,i)=>`<div class="setup-person"><div class="fruit">${f[1]}</div><b>${f[0]}</b><select data-seat="${i}"><option value="human">Human</option><option value="ai-easy">AI: Easy</option><option value="ai-normal" ${i?'selected':''}>AI: Normal</option><option value="off" ${i?'':'selected'}>Empty</option><option value="ai-hard">AI: Hard</option></select></div>`).join('')}
function newGame(){let chosen=$$('#playerSetup select').map((s,i)=>({seat:i,type:s.value})).filter(x=>x.type!=='off');if($('#fillAi').checked){for(let i=0;chosen.length<5&&i<5;i++)if(!chosen.some(x=>x.seat===i))chosen.push({seat:i,type:'ai-normal'})}if(!chosen.some(x=>x.type==='human')){alert('Choose at least one human rebel.');return}let max={easy:36,normal:30,hard:24}[$('#difficulty').value];game={players:chosen.map((x,n)=>({id:n,name:FRUITS[x.seat][0],fruit:FRUITS[x.seat][1],color:FRUITS[x.seat][2],ai:x.type.startsWith('ai'),level:x.type.split('-')[1]||'normal',pos:0,points:4,skip:0,immunity:0,boost5:0,boost3:0,extra:false})),current:0,clock:max,maxClock:max,phase:'roll',paused:false,over:false};show('gameScreen');buildBoard();render();startTurn()}
function buildBoard(){let b=$('#board');b.innerHTML='<div id="clock"><div class="crown">♛</div><strong>DOOMSDAY</strong><span id="clockNumber">30</span><small>turns remain</small><div class="clock-bar"><i id="clockFill"></i></div><em id="clockWarning">The Cado King watches.</em></div>';for(let i=0;i<=75;i++){let t=tileType(i),el=document.createElement('div');el.className='tile '+TYPES[t][0];el.dataset.pos=i;el.innerHTML=`<span class="num">${i}</span><span class="tile-label">${TYPES[t][1]}</span>`;b.appendChild(el)}game.players.forEach(p=>{let e=document.createElement('div');e.className='piece';e.id='piece'+p.id;e.textContent=p.fruit;b.appendChild(e)});positionTiles()}
function positionTiles(){let board=$('#board'),r=board.getBoundingClientRect();if(r.width<1||r.height<1)return;let cx=r.width/2,cy=r.height/2,inner=Math.min(r.width,r.height)*.28,outer=Math.min(r.width,r.height)*.44;$$('.tile').forEach(el=>{let i=+el.dataset.pos,progress=i/75,angle=(-120+progress*1080)*Math.PI/180,radius=inner+(outer-inner)*progress;el.style.left=(cx+Math.cos(angle)*radius)+'px';el.style.top=(cy+Math.sin(angle)*radius)+'px'})}
function posPiece(p){let t=$(`.tile[data-pos="${p.pos}"]`),e=$('#piece'+p.id);if(!t||!e)return;let a=t.getBoundingClientRect(),b=$('#board').getBoundingClientRect(),same=game.players.filter(q=>q.pos===p.pos),index=same.indexOf(p),angle=index*2*Math.PI/Math.max(same.length,1);e.style.left=(a.left-b.left+a.width/2+Math.cos(angle)*10)+'px';e.style.top=(a.top-b.top+a.height/2+Math.sin(angle)*10)+'px';e.classList.toggle('active',game.players[game.current]===p)}
function render(){if(!game)return;let p=game.players[game.current];$('#clockNumber').textContent=game.clock;$('#clockFill').style.width=(game.clock/game.maxClock*100)+'%';$('.clock-bar').classList.toggle('danger',game.clock<=8);$('#clockWarning').textContent=game.clock<=8?'MIDNIGHT NEARS!':'The Cado King watches.';$('#turnBanner').textContent=game.over?'Game over':`${p.fruit} ${p.name}'s turn${p.ai?' (AI)':''}`;$('#playerList').innerHTML=game.players.map((x,i)=>`<div class="player-card ${i===game.current?'active':''} ${x.skip?'dead':''}" style="border-left:5px solid ${x.color}"><span class="fruit">${x.fruit}</span><span class="name">${x.name}${x.ai?' 🤖':''}</span><small>Space ${x.pos} · ${x.points} pts ${x.skip?'· skipped next':''}${x.immunity?' · shield '+x.immunity:''}</small></div>`).join('');$('#shop').innerHTML=[['+5 this roll',4,'boost5'],['+3 for 2 rolls',5,'boost3'],['Shield (2 turns)',6,'immunity']].map(x=>`<button class="shop-item" data-buy="${x[2]}">${x[0]} — ${x[1]} pts</button>`).join('');game.players.forEach(posPiece);$('#rollBtn').disabled=game.phase!=='roll'||p.ai||game.over;$('#endBtn').disabled=game.phase!=='end'||p.ai||game.over;save()}
function startTurn(){if(game.over)return;let p=game.players[game.current];game.phase='roll';p.extra=false;if(p.skip){p.skip--;message(`${p.fruit} ${p.name} is blocked and loses this turn.`);render();setTimeout(nextTurn,1100);return}message(`${p.fruit} ${p.name}, roll the dice!`);render();if(p.ai)setTimeout(aiTurn,900)}
function roll(){let p=game.players[game.current];if(game.phase!=='roll'||p.ai)return;doRoll(p)}
function doRoll(p){game.phase='moving';$('#dice').classList.add('rolling');setTimeout(()=>{let a=1+Math.floor(Math.random()*6),d=1+Math.floor(Math.random()*6),bonus=p.boost5?5:(p.boost3?3:0);if(p.boost5)p.boost5=0;if(p.boost3)p.boost3--;$('#dice').innerHTML=`<b>${a}</b><b>${d}</b>`;$('#dice').classList.remove('rolling');let steps=a+d+bonus;message(`${p.fruit} rolled ${a+d}${bonus?' + '+bonus+' boost':''}!`);sound(440);moveAnimated(p,steps,()=>land(p));},600)}
function moveAnimated(p,n,done){let target=Math.max(0,Math.min(75,p.pos+n)),dir=Math.sign(target-p.pos),count=Math.abs(target-p.pos),i=0;let timer=setInterval(()=>{p.pos+=dir;posPiece(p);sound(260);if(++i>=count){clearInterval(timer);done()}},110)}
function move(p,n){p.pos=Math.max(0,Math.min(75,p.pos+n));}
function land(p){if(p.pos>=75){win(p);return}let type=tileType(p.pos);let text='A quiet stretch of road.';if(type==='roll'){p.extra=true;text='Roll Again! The rebel road calls for another turn.'}if(type==='back'){text='Back 5 spaces!';moveAnimated(p,-5,()=>finishLand(p,text));return}if(type==='swap'){let r=rival(p);if(r&&!r.immunity){swap(p,r);text=`Swapped with ${r.fruit} ${r.name}!`}else text='Swap blocked by a shield.'}if(type==='bad'){if(p.immunity){text='Bad luck deflected by your shield!'}else{p.skip++;p.points=Math.max(0,p.points-2);text='Bad Luck: lose 2 points and skip your next turn.'}}if(type==='event'){drawCard(p);return}finishLand(p,text)}
function finishLand(p,text){if(p.pos>=75){win(p);return}game.phase='end';message(text);render();if(p.ai)setTimeout(nextTurn,700)}
function drawCard(p){let card=EVENTS[Math.floor(Math.random()*EVENTS.length)],apply=()=>{closeModal();card[3](p);if(p.pos>=75){win(p);return}finishLand(p,`Event: ${card[0]}`)};$('#modalContent').innerHTML=`<div class="event-card"><div class="card-icon">${card[1]}</div><p class="eyebrow">Event Card</p><h2>${card[0]}</h2><p>${card[2]}</p><button id="cardOk" class="primary">Accept Fate</button></div>`;openModal();$('#cardOk').onclick=apply;if(p.ai)setTimeout(apply,1200)}
function rival(p){let others=game.players.filter(x=>x!==p);return others.sort((a,b)=>b.pos-a.pos)[0]||null}function swap(a,b){if(!b)return;[a.pos,b.pos]=[b.pos,a.pos]}
function nextTurn(){if(game.over)return;let p=game.players[game.current];if(!p.extra){game.clock--;game.players.forEach(x=>{if(x.immunity)x.immunity--});if(game.clock<=0){lose();return}}game.current=(game.current+1)%game.players.length;startTurn()}
function endTurn(){if(game.phase==='end')nextTurn()}
function buy(kind){let p=game.players[game.current],cost={boost5:4,boost3:5,immunity:6}[kind];if(p.ai||game.phase!=='roll'||p.points<cost)return;p.points-=cost;if(kind==='immunity')p.immunity=Math.max(p.immunity,2);else p[kind]+=(kind==='boost3'?2:1);message('Purchase made. Roll when ready.');sound(600);render()}
function aiTurn(){let p=game.players[game.current];if(!p.ai||game.over||game.paused)return;let choice=p.level==='hard'?(p.pos>60?'boost5':p.immunity?'': 'boost3'):p.level==='normal'&&p.pos>50?'boost5':'';if(choice&&p.points>=({boost5:4,boost3:5}[choice]))buyAi(p,choice);setTimeout(()=>{if(!game.paused)doRoll(p)},500)}function buyAi(p,k){p.points-={boost5:4,boost3:5}[k];p[k]+=(k==='boost3'?2:1)}
function win(p){game.over=true;game.phase='over';render();clearSave();$('#modalContent').innerHTML=`<div class="win"><div class="winner-fruit">${p.fruit}</div><h2>${p.name} Saves the Realm!</h2><p>The rebel reaches the finish before midnight. The Cado King’s reign crumbles!</p><button id="playAgain" class="primary">Play Again</button></div>`;openModal();$('#playAgain').onclick=()=>{closeModal();setup()};sound(800)}
function lose(){game.over=true;clearSave();render();$('#modalContent').innerHTML='<div class="win"><div class="winner-fruit">🥑👑</div><h2>The Cado King Wins</h2><p>Midnight strikes before a rebel can reach the goal. Start a new rebellion!</p><button id="playAgain" class="primary">Try Again</button></div>';openModal();$('#playAgain').onclick=()=>{closeModal();setup()};sound(120)}
function message(t){$('#actionText').textContent=t;$('#turnBanner').classList.add('turn-toast');setTimeout(()=>$('#turnBanner').classList.remove('turn-toast'),700)}function openModal(){$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}
function rules(){return `<div class="rules"><h2>Rules of AvacaDO</h2><h3>Goal & Setup</h3><p>Choose your rebel fruit and race from space 0 to the Goal at space 75. The Cado King wins if the central doomsday clock reaches zero.</p><h3>Turns & Movement</h3><p>On your turn roll two dice. Your piece moves automatically. Follow the landed tile, optionally buy one market item before rolling, then end your turn. Every normal completed turn lowers the clock by one. A “roll again” or certain card gives an extra turn without lowering it.</p><h3>Tiles</h3><p><b>EVENT</b> draws a card. <b>ROLL AGAIN</b> grants another turn. <b>BACK 5</b> moves you backward. <b>SWAP</b> trades places with the leading rival unless shielded. <b>BAD LUCK</b> costs 2 points and blocks your next turn, unless you have a shield.</p><h3>Cards & Abilities</h3><p>Twenty event outcomes can move rebels, alter points, block rivals, swap places, grant shields, or restore two clock turns. Spend points before rolling: +5 this roll (4), +3 for two rolls (5), or a two-turn shield (6).</p><h3>Winning</h3><p>The first rebel to reach or pass space 75 wins immediately. If all clock turns expire first, the Cado King ends the realm.</p></div>`}
function sound(freq){if(localStorage.avacadoMute==='1')return;try{let c=audio||(audio=new AudioContext()),o=c.createOscillator(),g=c.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.04,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.11);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.12)}catch(e){}}
$('#newGameBtn').onclick=setup;$('#backBtn').onclick=()=>show('startScreen');$('#startBtn').onclick=newGame;$('#rollBtn').onclick=roll;$('#endBtn').onclick=endTurn;$('#restartBtn').onclick=()=>{if(confirm('Restart this game?'))setup()};$('#resetSaveBtn').onclick=()=>{clearSave();message('Saved game removed.')};$('#closeModal').onclick=closeModal;$$('[data-open="rules"]').forEach(b=>b.onclick=()=>{$('#modalContent').innerHTML=rules();openModal()});$('#shop').onclick=e=>{let b=e.target.closest('[data-buy]');if(b)buy(b.dataset.buy)};$('#pauseBtn').onclick=()=>{if(game.over)return;game.paused=true;$('#modalContent').innerHTML='<div class="pause"><h2>Game Paused</h2><p>The rebels catch their breath.</p><button id="resume" class="primary">Resume</button></div>';openModal();$('#resume').onclick=()=>{game.paused=false;closeModal();if(game.players[game.current].ai)aiTurn()}};$('#muteBtn').onclick=function(){localStorage.avacadoMute=localStorage.avacadoMute==='1'?'0':'1';this.textContent=localStorage.avacadoMute==='1'?'🔇':'🔊'};$('#musicBtn').onclick=function(){this.classList.toggle('on');this.textContent=this.classList.contains('on')?'♫ Music On':'♫ Music'};window.addEventListener('resize',()=>{if(game){positionTiles();game.players.forEach(posPiece)}});if(localStorage.getItem('avacadoSave'))$('#continueBtn').classList.remove('hidden');$('#continueBtn').onclick=()=>{try{game=JSON.parse(localStorage.avacadoSave);show('gameScreen');buildBoard();render();startTurn()}catch(e){clearSave()}};
